src/components/calculator/PointsDisplay.tsx, src/components/calculator/SelectControl.tsx, src/pages/Home.tsx
=> Add tooltip for risk tolerance and default to 1%

src/App.tsx, src/components/Analytics.tsx, src/pages/Calculator.tsx
This will tell us how many times users are changing the calculator.
=> Add analytics for users interracting with the calculator.

src/components/Analytics.tsx, src/pages/Calculator.tsx, src/styles/App.scss
Avoids needing to change overflow.
=> Implement sticky results bar in javascript.

src/data/calculate.ts
Hotfix part 1: don't crash if calculate() raises an exception
=> Fix crash with outdated local storage data

src/data/__tests__/calculate.test.ts, src/data/prepopulated.ts
After our trichotomy update, I think grocery stores should look a bit less scary than this.
=> People do wear bandanas in grocery stores

src/paper/1-intro.ts
I really thought I had done this already but must've lost it when I lost work somehow in the final sprint!
=> Ben Shaya to authors list!

src/components/calculator/ActivityRiskControls.tsx, src/components/calculator/PointsDisplay.tsx, src/data/calculate.ts, src/pages/Paper.tsx
=> Compare total risk to risk budget.

src/data/__tests__/calculate.test.ts, src/data/data.ts
Also add a regression test for calculating regional person risk.
Fixes: #209
=> Make risk profiles self-consistent, and use them as a regression test.

src/components/calculator/ActivityRiskControls.tsx, src/data/calculate.ts, src/data/localStorage.ts, src/pages/Calculator.tsx
This should hopefully prevent future issues like #170. It also adds a customization point where we can do smarter fixes than "change the corresponding field to nothing-selected-yet".
=> Fix part 2 for outdated local storage data: fix it up when loading it

src/App.tsx, src/pages/About.tsx
/calculator will redirect to home.
Fixes: #239
=> Point landing page to Calculator, move old home to About.

src/data/__tests__/calculate.test.ts, src/data/data.ts, src/data/prepopulated.ts
bifurcate hooking up with rando from partner.
Fixes: #173
Fixes: #190
=> Add cuddling option at 2x transmission rate, 

src/components/calculator/PointsDisplay.tsx
=> Fix expression not getting evaluated

public/index.html
=> Add OpenGraph tags so that facebook shares will have a description and image

src/paper/9-advanced-method.ts
=> Clean up advanced method explanation. 

src/data/data.ts
Added meter tekst to distance selection.
=> added metric units (feet to meter)

package.json, src/components/calculator/ActivityRiskControls.tsx, src/components/calculator/PersonRiskControls.tsx, src/components/calculator/SelectControl.tsx, src/data/data.ts, src/paper/13-q-and-a.ts, yarn.lock
I whipped this up.
I think it's worth publishing as-is just to have something out in the wild to make it more usable.
AND I think it would be better to do something like "1/20th the risk" instead of "0.05x risk".
So I'm gonna play with that.
Fixes #229
=> Make risk modifiers visible. 

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/SelectControl.tsx, src/data/queryParams.ts
Also does stricter sanity checking within PrevalenceControls, such that this
it will be resilient unsanitzed data in the future.
Fixes: 317
=> Don't pass undefined variables from QueryParams.

src/components/calculator/PointsDisplay.tsx
=> Fix 'each time' after points display. 

src/components/calculator/PrevalenceControls.tsx
=> Show 'Entire state' instead of 'entire country'. 

src/components/calculator/ActivityRiskControls.tsx, src/components/calculator/PointsDisplay.tsx, src/pages/Calculator.tsx
Cleanup from PR #338 that didn't make it in.
Going to merge immediately.
=> Cleanup from PR #338 that didn't make it in.

src/components/calculator/ExplanationCard/ExplanationCard.tsx
=> Fix typo: select -> selected

src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/pages/Calculator.tsx
(Next time I'll make these separate PRs. 🙊  I get how you're doing it now.)
=> UX Redesign: A few small cleanups

src/components/calculator/PointsDisplay.tsx
Add extreme risk category. Fixes #363
=> UX Redesign: Add extreme risk category

package.json, src/components/AutoAlert.tsx, src/pages/Calculator.tsx, yarn.lock
Adds a button to copy the shareable URL.
Updated from #373 (which is adopted from #313)
=> Share by link

src/components/calculator/PointsDisplay.tsx, src/styles/App.scss
=> Keep the thermometer in the page for dangerously high and extreme categories

src/components/calculator/PointsDisplay.tsx, src/styles/App.scss
=> Make points more prominent. 

src/components/Expandable.tsx, src/components/FirstTimeUserIntroduction.tsx, src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/components/calculator/PrevalenceControls.tsx, src/styles/App.scss
Fixes #386 
(I know, the two refactor commits should probably be in a different PR. But I wanted to just knock them out on this branch. Let me know if you want me to separate them.)
=> Cleanup new user intro and refactor collapse into component.

src/pages/Calculator.tsx
=> Add url params back at all times

src/components/calculator/util/FormatPrecision.ts, src/components/calculator/util/__tests__/FormatPrecision.test.ts
=> Fix fixed point formatting.

src/components/calculator/ControlLabel.tsx, src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/components/calculator/RadioControl.tsx, src/components/calculator/SelectControl.tsx, src/data/data.ts
=> Fix risk budget labels. 

src/components/calculator/PointsDisplay.tsx, src/styles/App.scss
=> Add sixth level to thermometer

src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/components/calculator/RadioControl.tsx, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts, src/data/prepopulated.ts, src/data/queryParams.ts, src/pages/Calculator.tsx, src/styles/App.scss
Cleaning up PR #411 by doing a rebase.
Fixes #399
=> Add risk budget to data model

src/pages/Calculator.tsx
=> Remove query params on form refresh. Fixes #410

src/components/calculator/SavedDataSelector.tsx, src/pages/Calculator.tsx
=> Add guidance saved scenario & properly reset "saved scenario" when form resets

src/components/calculator/PersonRiskControls.tsx
=> Improve the feedback when listing a larger number of people

package.json, yarn.lock
=> Remove precommit and prepush hooks. Leave it up to CI.

src/components/calculator/PersonRiskControls.tsx, src/data/__tests__/calculate.test.ts, src/data/prepopulated.ts
=> Update "Large Party" prepop and person risk guidance to reflect 15 foot radius.

src/components/calculator/CopyToSpreadsheetButton.tsx, src/components/calculator/PrevalenceControls.tsx
=> Add copy to spreadsheet button. Fixes #432

src/components/IosOptgroup.tsx, src/components/calculator/SavedDataSelector.tsx, src/components/calculator/SelectControl.tsx
This makes ios display multiline options.
=> Add empty optgroup to end of selects

src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts
=> Add 1% and 0.1% risk profile. 

src/components/calculator/ExplanationCard/ExplanationCard.tsx
- Fix help text re changing to partner / housemate
=> Fix distance explanation

src/App.tsx, src/components/MarkdownPage.tsx, src/posts/blog/index.ts
- Remove og:url
- Change the url of the blog post.
=> remove opengraph url

src/components/calculator/PrevalenceControls.tsx, src/data/data.ts, src/data/queryParams.ts
=> Add custom entry params to share url.

public/_headers, src/posts/blog/1-ux-redesign/ux-redesign.ts
Also make it easier to get to the calculator from the blog post on mobile.
Fixes: #175
=> Fix navigation menu icon on Android.

src/components/calculator/PersonRiskControls.tsx, src/locales/en.json, src/locales/hu.json
A typo broke it, re-added the warning added in ad09811b015
=> i18n: fixed the large group warning

src/App.tsx, src/locales/en.json, src/locales/hu.json, src/pages/Calculator.tsx
=> Fix missing key after nesting the translation file

src/components/calculator/ActivityRiskControls.tsx
=> Add wider text box for environment field.

src/pages/Contact.tsx
Just a description and a link to Weblate. It might help us get translators for more languages.
=> i18n: added a call-to action to "Contact Us"

src/locales/en.json
Add "The first step in protecting your family and community is to avoid getting COVID yourself."
=> Emphasize protecting others

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/SelectControl.tsx, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/prepopulated.ts, src/locales/en.json, src/posts/paper/14-research-sources.ts, src/posts/paper/7-basic-method.ts
Use the model developed by https://covid19-projections.com/estimating-true-infections-revisited/
=> Update Adjusted Prevalence Model

update_prevalence.py
Update underreporting function to match PR #564. 
See #567.
Closes #565.
=> Update CSV export underreporting function to match calculator

src/App.tsx, src/i18n.tsx
This depends on #577. Also, please don't merge it until I could have the volunteer who reviewed most of the translation itself check it out live -- creating this pull request was the easiest way to generate a publicly available preview on Netlify.
=> i18n: added Czech translation

.github/workflows/ci.yml
`pod-docs` will be the feature branch where I'd like to get everything ready for the new spreadsheet & pod documentation.
=> Prepare for pod docs feature branch

src/components/calculator/SelectControl.tsx, src/components/markdown/BlogPostPage.tsx, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts, src/locales/en.json, src/pages/Calculator.tsx, src/pages/styles/Paper.scss, src/posts/blog/5-b117/b117.ts, src/posts/blog/index.ts, src/posts/paper/99-changelog.ts, src/posts/post.ts
Apply 1.5x multiplier on one-time activities to account for B117 / VOC202019/01
=> Increase Activity Risk in response to B.1.1.7.

src/components/calculator/FirstTimeUserIntroduction.tsx, src/pages/Calculator.tsx, src/styles/App.scss
=> Add survey message to calculator page. Add icon to b117 alert

src/posts/paper/99-changelog.ts
=> Fix date typo on changelog

src/pages/Calculator.tsx
=> Fix copy URL bug

src/App.tsx, src/i18n.tsx
The Spanish translation is now complete, time to add it to the language selector!
=> i18n: added Spanish locale to the selector

src/components/calculator/PrevalenceControls.tsx
Just a copy of #657 from @david-mears-dfe
=> Fix PrevalenceFields' display logic

src/posts/tracker/quickstart.ts
=> Encourage people to subscribe more directly in the Risk Tracker quickstart docs

src/pages/Calculator.tsx
This fixes a broken link on the main page.
=> Remove extraneous paren

src/pages/RiskTracker.tsx
Reverts microcovid/microcovid#790
=> Revert "Add tracker@microcovid.org email address to docs"

public/tracker/vaccine_table.csv, src/data/__tests__/calculate.test.ts, src/data/data.ts, src/locales/en.json, src/pages/Calculator.tsx, src/posts/paper/13-q-and-a.ts, src/posts/paper/14-research-sources.ts, src/posts/paper/99-changelog.ts
Includes Johnson & Johnson + moderna/pfizer update.
Updates both Calculator and Risk Tracker.
=> Update vaccines with new research.

src/locales/en.json
I messed up in #825 and broke the survey alert. This fixes it.
=> Sputnik survey fix

src/posts/paper/13-q-and-a.ts
=> Fix typo in Q&A doc

update_prevalence.py
The JHU dataset is not strictly increasing case numbers (perhaps due to governments
correcting their numbers?). If a correction happens, compute # of cases in a week as
max(cumulative_cases_past_week) - min(cumulative_cases_past_week)
It is difficult to know if this is over or underestimating the actual number of cases,
since we have no way to determine the relative magnitudes of the correction vs the #
of new cases.
=> Make update_prevalence more robust to negative daily cases

src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/locales/en.json, src/pages/Calculator.tsx, src/posts/paper/99-changelog.ts, update_prevalence.py
- Update prevalence calculation based on 10 December 2020 Covidestim model.
- Update prevalence calculation based on COVID19 Projections' December 10 update
=> Update true infections formula

src/data/calculate.ts, src/data/data.ts, src/data/prepopulated.ts, src/data/queryParams.ts, src/locales/en.json
=> Add theirVaccine to data model

src/posts/paper/99-changelog.ts
=> Fix off-by-one month in changelog

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/prevalence/LocationPrevalenceDetails.tsx, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/prepopulated.ts, src/locales/en.json
Only affects "average" risk profiles. More thought needed for supporting
calculated risk profiles.
=> Add theirVaccine to calculator core.

update_prevalence.py
This reverts commit dd642dcd182b6a35337c4a5fe699a65ef8998a38.
=> Revert "Automatic prevalence update 2021-06-17 (#878)"

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/prevalence/LocationPrevalenceDetails.tsx, src/data/calculate.ts, src/data/locationHelpers.ts, src/data/prepopulated.ts
This will make it easier to support manual entry vaccine prevalence.
- Move location data fetching into a helper function.
- Store %fully vaccinated in CalculatorData
=> locationhelpers

package.json, yarn.lock
Can someone with a Mac make sure this doesn't bork anything?
rm -rf node_modules
yarn install
=> Replace node-sass with sass

src/data/__tests__/queryParams.test.ts, src/data/calculate.ts, src/data/queryParams.ts, src/pages/__tests__/Calculator.test.tsx
This commit also cleans up malformed query parameters.
=> Gracefully handle missing scenarioName in URLs.

src/posts/paper/13-q-and-a.ts
=> Nit: fix typo in whitepaper Q&A

src/components/calculator/PrevalenceControls.tsx
Sort the `subLocationOptions` and `subSubLocationOptions` alphabetically
=> Sort subLocations and subSubLocations in the dropdown

.github/workflows/prevalence.yml, scripts/prevalence_helper.sh
=> Use microCOVID bot instead to run prevalence updates

update_prevalence.py
I was wrong about the required format, and the one I had caused it to fail to parse at all, causing the adjusted prevalence to be 0 everywhere
=> Fix updatedAt format

public/tracker/vaccine_table.csv, src/components/RiskTrackerUtil.tsx, src/data/__tests__/calculate.test.ts, src/data/data.ts, src/index.tsx, src/locales/en.json, src/pages/Calculator.tsx, src/pages/__tests__/Calculator.test.tsx, src/posts/paper/99-changelog.ts
Added new multipliers for boosted vaccines + Omicron
=> Omicron vaccine multipliers

src/data/calculate.ts
@beshaya - Here is the fix for issue 1291 the URL query string not allowing 3 vaccine doses
=> Fixing issue 1291 (allow 3 vaccine doses)

update_prevalence.py
=> Discard county-level data on validation error for Canada/Romania

update_prevalence.py
This is a crude mechanism to filter logs based on the population of the area affected to help us focus attention span and logging tool quota on the most important issues to address.
=> Use population as a method to determine log level of data issues

update_prevalence.py
Fixes issue seen in https://github.com/microCOVID/microCOVID/actions/runs/3155887853/jobs/5135024251
=> More retry logic fixes

src/locales/en.json
Simplest change that leaves the field available for future text insertions. Translations will propagate automatically via Weblate
=> issue #1084

test_update_prevalence.py, update_prevalence.py
Ignore attempts to load data for places not in JHU place facts - JHU
does not recognize 'counties' inside the Northern Mariana Islands
=> Suppress another expected warning log

test_update_prevalence.py, update_prevalence.py
=> Add aggregated population-based logging in update_prevalence.py

test_update_prevalence.py, update_prevalence.py
Differentiate issues that drop county-level data vs state-level data.
=> Improve WARNING log issue aggregation summaries

test_update_prevalence.py, update_prevalence.py
This is a refactor towards being able to add data quality spot-checks from previous dates as well.
=> Factor out some Python date arithmetic to a new class

.gitignore, mypy.ini, requirements-manual.txt, update_prevalence.py
* Tighten up mypy rules and add a related needed hint
* Write out type coverage report to typecover/index.html for debugging
* Upgrade to latest version while I'm here
=> Various mypy improvements

update_prevalence.py
The parse_canada_prevalence_data() function uses a variable called
'place' twice - once while working through health-region-level data,
once while working through province-level data.  This bit me at least
once in a draft refactor, so let's go ahead and use two different
variables.
=> Clarify 'place' variable in parse_canada_prevalence_data()

test_update_prevalence.py, update_prevalence.py
Also clean up a logging message
=> Fix add_increasing_cumulative_cases() in tests and use more

test_update_prevalence.py, update_prevalence.py
I'm not quite sure about the intention/soundness of the logic in
rollup_testing(), so let's assert that the condition I'm concerned
about never happens.
=> Validate logic in rollup_testing()

src/locales/en.json, src/pages/Calculator.tsx, src/posts/paper/1-intro.ts
See:
* https://github.com/microCOVID/microCOVID/discussions/1791
=> Add shutdown alert
