src/components/calculator/ActivityRiskControls.tsx, src/data/__tests__/calculate.test.ts, src/data/data.ts, src/data/prepopulated.ts
Fixes: #137
Updates mask labels to be clear and user-friendly. Links from calculator to relevant research source section. Clearly lists cotton masks as "basic" masks, and reduces wearer protection from 2x to 1x for these.
I think this is sufficient for #159 (the wording is clear enough to answer most of the user questions we're seeing). I added a popover box to link to the relevant research section. Note that the research sources section cites Chu and states 2x wearer protection for basic masks while the calculator is using 1x.
=> Update masks to trichotomy: none, cotton, filtered

src/pages/Paper.tsx
The way the HTML was getting parsed to "toteach" into "to teach"
Fixes #183
=> Fix spacing issue "toteach" → "to teach"

src/components/calculator/PointsDisplay.tsx
Suggest more clearly that we're rounding to one sig fig in indicating how much risk allocation one is using up.
=> Add tildes to risk allocation

src/App.tsx
Now that there's a dropdown, and people mostly won't use the TOC page, it'll be harder for people to discover that there's an "all in one page" option. Adding it to the menu.
=> Add "all on one page" to dropdown

package.json, src/App.tsx, src/components/ScrollToTop.tsx, src/data/calculate.ts, src/data/queryParams.ts, src/pages/Calculator.tsx, yarn.lock
It's currently hard to share microcovid results for a specific set of assumptions. It would be really nice to, say, link to the assumptions for the presidential debate. This PR adds the use-query-param library and automatically updates query params based on changes to the form for easy sharing.
* Add user-query-params library, upgrade query-string
* Create a configuration for query parameters
* Update query parameters whenever calculator changes
* Adjust scroll behavior to avoid changing variables
=> Add query variables for easy linking

src/components/calculator/PointsDisplay.tsx, src/data/FormatPrecision.ts, src/data/__tests__/FormatPrecision.test.ts, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/pages/Calculator.tsx
* Compute risk as 1 - (1 - risk_each) ^ N if we would otherwise show 10%
* Note that this allows us to show "1 housemate with covid = 30%"
* Augment display functions to show more sigfigs when close to 1e6
Fixes: 331
=> Allow the calculator to display numbers closer to 1e6uCoV

src/styles/App.scss
Text under "nearby people" was cut off without some padding.
=> UX Redesign: Fix styling bug underneath calculator accent headers

src/data/data.ts
Now that we've removed "200 microCOVIDs per week" in the main calculator results, it'd be great if it was more visible and not just buried in "How was this calculated?"
=> Add "200 microcovids per week" to radio buttons

src/data/data.ts
This leaves one inconsistency with whether you write `microCOVIDs/week` or `microCOVIDs per week`.
=> Fix spelling error and inconsistent capitalization

src/locales/en.json, src/locales/hu.json
This closes #457 and now merges cleanly onto the new main branch.
Both notes refer to your own mask, but others eating and drinking should only affect their own mask usage, not yours.
=> Fixing the note around mask usage and eating (#457)

src/pages/Calculator.tsx
Fixes the URL copied, it had a new line in the middle.
Expected:
```
https://www.microcovid.org/distance=sixFt&duration=180&interaction=oneTime&personCount=6&riskProfile=average&setting=outdoor&subLocation=US_08117&theirMask=basic&topLocation=US_08&voice=normal&yourMask=filtered
```
Observed:
```
https://www.microcovid.org/
?distance=sixFt&duration=180&interaction=oneTime&personCount=6&riskProfile=average&setting=outdoor&subLocation=US_08117&theirMask=basic&topLocation=US_08&voice=normal&yourMask=filtered
```
=> [calculator] fix copy share button spacing

src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/components/calculator/SelectControl.tsx, src/data/__tests__/RiskProfile.test.ts, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts, src/data/prepopulated.ts
- Create a feature branch for work to help with high prevalence situations + add to CI
- Breaks down RiskProfile calculation in individual's actions, # of housemate's, # of other traceable contacts; standardizes how RiskProfile is calculated
- Adds hooks for adding "symptom free" features
That this change makes no user-facing changes (except adding a new parameter in the url) - verified by calculate.test.ts
=> Break down RiskProfile calculation

src/posts/paper/14-research-sources.ts
A link in `paper/14-research-sources` had flipped markdown braces.
=> Fix a broken markdown link

src/components/calculator/CopyToSpreadsheetButton.tsx
No longer needed. It was only a stopgap measure before we had automatic prevalence data imports.
=> Remove copy to spreadsheet button

src/App.tsx, src/i18n.tsx
There is now a fairly complete and well-reviewed Norwegian (Bokmål) translation available on Weblate, so it was time to add it to the language selector.
=> i18n: added Norwegian translation to the selector

src/components/calculator/PrevalenceControls.tsx
@blanchardjeremy [says](https://github.com/microcovid/microcovid/pull/326\#issuecomment-760626478):
> After the user types in the manual data, I think they should see the actual
prevalence and adjusted prevalence numbers still.
This commit removes the logic which hides the calculated prevalence numbers during manual data entry mode.
=> Show results of prevalence calculation when in manual data mode

src/components/calculator/PersonRiskControls.tsx
With ccbfa0fe the description above the input field already contains the "within 15 feet" request so this is redundant, and it was also never localized, so let's just get rid of it.
=> Remove "Within 15 feet" tooltip from People input

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/SavedDataSelector.tsx, src/locales/en.json, src/pages/Calculator.tsx
It was previously below the call to action.
Make some related UX tweaks too:
* adjust header styles to deemphasize location and highlight
activity/relationship now that location autofills
* remove explicit step numbers now that location autofills
* adjust prebuilt activities box instructions so that the most important
words for understanding are clustered at the beginning of the phrase
* add magnifying glass affordance to prebuilt activity search to more
strongly indicate that it's for typing (it's indistinguishable from
the other dropdowns. This isn't a perfect solution but will do for now.)
=> Move prebuilt activities to the person-risk card.

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/SavedDataSelector.tsx, src/locales/en.json
* Add custom error message encouraging people to modify calculator
values directly if there is no preset.
* Disable autofill addresses on the country, state and activity search
typeaheads.
* Make the "switch to manual data entry mode" button smaller and boring
(like an email unsubscribe button) so that people are less likely to
hit it on autopilot
* Hide details if someone clicks "Switch to pre-populated location
data". If someone is clicking on this button they probably want to
reset back to the previous view.
=> Small miscellaneous UX tweaks in prevalence box and activity search

package.json, src/components/calculator/PrevalenceControls.tsx, src/data/location.ts, update_prevalence.py, yarn.lock
This mostly works, but there are a few things to iron out before it could be merged:
- The "United States (all)" selection does not have the "(all)" postfix any more which can be confusing
- this would need to be merged immediately after a prevalence update patch to ensure the diff for `location.ts` is readable: as it's a generated file, manually staging just the relevant changes would infeasible.
Let me know your thoughts.
=> i18n: localized country selector

src/components/calculator/ExplanationCard/maskDetails.tsx
From a report from @octern 
> Probable bug: the "learn more about masks" collapsible doesn't cause a cursor change on hover.
=> Switch mask info section on explanation card to use our existing component

src/components/calculator/PrevalenceControls.tsx, src/components/calculator/prevalence/LocationPrevalenceDetails.tsx, src/components/calculator/prevalence/ManualPrevalenceDetails.tsx, src/components/calculator/prevalence/PrevalenceResult.tsx, src/components/calculator/styles/PrevalenceControls.scss, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts, src/data/prepopulated.ts, src/data/queryParams.ts, src/locales/en.json, src/pages/Calculator.tsx
* when toggling data entry mode, keep country/state/county information
but mark it as disabled
* previously, the button would jump away from user's cursor position,
causing some confusion. Now it stays still.
* previously, hitting the manual data entry button would clear
existing location data. This isn't ideal for someone exploring the
interface by clicking on everything.
=> Toggle prevalence manual data entry with a checkbox.

src/components/calculator/FirstTimeUserIntroduction.tsx, src/locales/en.json, src/pages/Calculator.tsx, src/pages/__tests__/Calculator.test.tsx, src/pages/styles/Calculator.scss
Based on user testing feedback:
> UX Interview observation: Users were frequently derailed by the "Model Update" box at the top of the page. One of them said she didn't know what it meant, so she assumed the site wasn't for people like her. Another one did know what it meant but still saw it as being so technically detailed that she assumed the site wasn't for her.
> Could we consider moving updates and non-essential information to a sidebar? (several users also mentioned the conspicuously empty space on the right side of the page)
This is my first take on it. @octern is going to draft up something that he put more thought into and we can use the PR to implement whatever he/we comes up with.
=> Cleanup front page intro text

src/components/calculator/ExplanationCard/ExplanationCard.tsx, src/components/calculator/FirstTimeUserIntroduction.tsx, src/components/calculator/SavedDataSelector.tsx, src/components/calculator/controls/ControlLabel.tsx, src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/data/data.ts, src/data/prepopulated.ts, src/locales/en.json, src/pages/Calculator.tsx, src/pages/__tests__/Calculator.test.tsx, src/pages/styles/Calculator.scss
* adjust interaction type text
* move chance of transmission out of dropdown into calculator body
* signal what's coming in the rest of the calculator
* update calculator page test and fix warning
* add custom scenario option to the typeahead
I pulled this out of draft #741 because it was getting kind of large and messy.
=> Reword interaction type prompt

src/App.tsx, src/i18n.tsx
The coverage of the translation dropped to 60%, making it very
confusing. Removing it temporarily until translators on Weblate have a
chance to catch up.
This reverts commit 362ccdd799ad7ddd86b288019ed0b19fc3f2a888.
=> i18n: removing Norwegian translation from the selector

src/components/RiskTrackerUtil.tsx, src/pages/RiskTracker.tsx
Move the version number next to the spreadsheet URL so we can change everything at once.
=> Easier Risk Tracker release process

src/posts/paper/13-q-and-a.ts
I'm assuming this is an error, since immediately below, it says the Moderna vaccine's multiplier is 0.1, not 0.2.
=> Fix error in vaccine text

update_prevalence.py
The offending data that prompted this fix looked like this:
Alameda: daily cumulative cases pulled July 25 2021 with
now = datetime(2021, 7, 25, 12, 0, 0, 0) - timedelta(days=1)
[91028, 91197, 91546, 91743, 91937, 92091, 92372,
92580, 92584, 92973, 93361, 97459, 93953, 94345]
=> Use most recent cumulative case count for case count per week

src/components/calculator/SavedDataSelector.tsx
It was searching by identifier keys like outdoorMasked2 rather than
"Outdoor masked hangout with 2 other people".
=> Fix preset scenario search.

src/pages/Contact.tsx
- Fix github capitalization
- Add press email address
Closes #954
=> Add press@microcovid.org email address to contact page

update_prevalence.py
Test positivity rate is nullable, so just set it to None if we get an invalid value and log the issue to Sentry instead of blocking the whole update.
=> Handle invalid test positivity rates

src/posts/paper/99-changelog.ts
The Date() constructor counts months from 0 to 11, unfortunately.
This changelog entry was added on January 4, 2022 in commit 5c22fbb as part of
PR #1286. Other recent changelog entries appear to have correct months.
=> Fix month and typo in changelog

src/data/__tests__/calculate.test.ts, src/data/data.ts
J&J multiplier was mistakenly listed as .95x for 1 dose with no option for 2 doses. It should have been .95x for 2 doses and 1x for 1 dose.
https://www.medrxiv.org/content/10.1101/2021.12.28.21268436v1.full.pdf
Fixes: #1317
=> Fix J&J multipliers

update_prevalence.py
Fixes #1353.
When I run this manually, I get these two warnings (which would
previously cause the run to fail):
```
Discarding country Antarctica due to error: ValueError("Missing population data for Country(fullname='Antarctica', name='Antarctica', population=0, test_positivity_rate=None, cumulative_cases=Counter({datetime.date(2022, 2, 12): 11, datetime.date(2022, 2, 11): 11, datetime.date(2022, 2, 10): 11, datetime.date(2022, 2, 9): 11, datetime.date(2022, 2, 8): 11, datetime.date(2022, 2, 7): 11, datetime.date(2022, 2, 6): 11, datetime.date(2022, 2, 5): 11, datetime.date(2022, 2, 4): 11, datetime.date(2022, 2, 3): 11, datetime.date(2022, 2, 2): 11, datetime.date(2022, 2, 1): 11, datetime.date(2022, 1, 31): 11, datetime.date(2022, 1, 30): 11, datetime.date(2022, 1, 29): 11, …
```
=> Warn, don't error, on cases without population.

.github/workflows/prevalence.yml
Turns out failure emails go to whoever most recently turned on the
GitHub action.  Still me, but no longer tied to GitHub changes, so it
doesn't make sense to track in this file.
=> Drop an incorrect comment

update_prevalence.py
The lack of them is causing some WARNING logs:
```
WARNING: Could not find UID 583
WARNING: Could not find UID 585
```
I was able to run prevalence to completion, so I assume the original
issues that caused these places to be suppressed are resolved:
https://github.com/microCOVID/microCOVID/commit/f3d56e7c95abd69800e0f74b19653fb478bd1a71
https://github.com/microCOVID/microCOVID/commit/033d61c28f07d5f1ee624e52a498ac55088f2e67
=> Allow back Micronesia and Palau

test_update_prevalence.py, update_prevalence.py
JHU provides these as 'states' in time_series_covid19_vaccine_us.csv
but does not map them back in UID_ISO_FIPS_LookUp_Table.csv
Not being location-based categories, they wouldn't be helpful for
microCOVID users regardless, so silently ignore them.
=> Don't log when encountering known unknown locations from JHU

src/locales/en.json, src/pages/Calculator.tsx, src/posts/paper/99-changelog.ts
The calculator changelog formatting was not showing up correctly, and
there was no entry in the alerts section for the
covid19-projections.com update.
=> Fix up changelog and add entry in alerts section for #1421

update_prevalence.py
Hello,
As part of an effort to improve the consistency of file naming in [`CovidTimelineCanada`](https://github.com/ccodwg/CovidTimelineCanada), the file `geo/health_regions.csv` has been renamed `geo/hr.csv`. The old file will exist as a duplicate for the foreseeable future, but I figured it was best to be proactive and open up at PR for this.
Note that I also added a "PRUID" column to the health regions file some time ago, but this doesn't seem to have disrupted your updates at all.
See ccodwg/CovidTimelineCanada#62 for more information
=> Update link to Canadian health regions file

src/data/__tests__/calculate.test.ts, src/data/calculate.ts, src/locales/en.json, src/pages/Calculator.tsx, src/posts/paper/7-basic-method.ts, src/posts/paper/99-changelog.ts, test_update_prevalence.py, update_prevalence.py
This reverts #1421 until we can validate the change further.
The PR changed our prevalence ratio formula from:
`1000/(day_i + 50) * (positivity-rate)^0.5 + 1`
to
`1500/(day_i + 50) * (positivity-rate)^0.5 + 1`
However, I do not believe that reflects the actual March 2, 2021 update on the referenced paper.  In fact, I believe it rolls us back to a formula used prior to the December 10th, 2020 update:
> December 10, 2020 Update: We adjusted the constant in the prevalence ratio formula from a = 1500 / (day_i + 50) to a = 1000 / (day_i + 10). This results in a slightly higher prevalence ratio in the beginning of the pandemic and a lower prevalence ratio currently.
I believe that the author of the PR assumed that the update notices at the top of the paper indicated that the contents had been …
=> Revert #1421

conftest.py, test_update_prevalence.py
This mostly exercises mocking the rest of the update_prevalence.py script and takes the first opportunity to bail out via a realistic validation failure.
=> Add first test of main() method

test_update_prevalence.py, update_prevalence.py
It looks like a sign error resulted in two more days of JHU daily reports being pulled than are actually used in the application.
Verified by:
* ensuring that we have an exception raised when fewer than 8 of days are used to calculate a week's cases (see asserts in https://github.com/microCOVID/microCOVID/pull/1722).
* Running update_prevalence.py before and after and verifying no changes in data generated.
This was an inconsistency that was holding back refactors in how we deal with history fetching.
=> Remove fetches from JHU for unused days of history

update_prevalence.py
Similar to JHU in https://github.com/microCOVID/microCOVID/pull/1724, it looks like a sign error resulted in two more days of api.covid19tracker.ca daily reports being pulled than are actually used in the application.
Verified by:
* ensuring that we have an exception raised when fewer than 8 of days are used to calculate a week's cases (see asserts in https://github.com/microCOVID/microCOVID/pull/1722).
* Running update_prevalence.py before and after and verifying no changes in data generated.
=> Remove fetches from api.covid19tracker.ca for unused days of history

test_update_prevalence.py
This was slowing down runs of update_prevalence.py locally
=> Don't save the cache from tests to actual disk

test_update_prevalence.py, update_prevalence.py
This removes the general warning about lack of cases now that more
specific warnings.  These specific warnings will hopefully lead to
ways to salvage data or add more helpful warnings for the user.
=> Remove no-case warnings now that we have more actionable warnings

.gitignore, .pre-commit-config.yaml, README.md, model_comparison.ipynb, requirements-manual.txt, src/data/__tests__/scenarios.test.ts
In this change, just the collection of model outputs for a grid of various inputs. Comparison tk soon with a jupyter notebook or the like. Can you recommend an older revision to try this change against to see what effect past model changes have had?
Regarding the issue I had previously with running scripts: I wound up just going with a test that dumps out a file as a side effect. It was easier than getting too into it.
=> Save model predictions for a variety of scenarios for later analysis.

.gitignore, src/components/calculator/prevalence/ManualPrevalenceDetails.tsx, src/locales/en.json
- Please see [here](https://github.com/microCOVID/microCOVID/issues/1826) for source of changes.
- Hide specific fields from view (but keep in the page)
- Hardcode some of the newly hidden values so that all previous values are "wiped out" and are not affecting the calculation
- Show a Warning if Population field is not exactly 100k.
=> #1826 - Manual prevalence entry v1 proposal
